News: 
# https://www.w3school.com.cn/cssref/css_selectors.asp
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 百度热搜
    ListUrl: "https://top.baidu.com/board?tab=realtime"
    RawListUrl: "https://top.baidu.com/board?tab=realtime"
    Item: ".category-wrap_iQLoo "
    NewsUrl: ".title_dIF3B  "
    Title: ".c-single-text-ellipsis "
    Rank: ".index_1Ew5p "
    Author: ""
    PublishTime: ""
    Abstract: ".large_nSuFU "
    IsHot: ".c-text-hot_3ZhI9 "
    ImgUrl: ".img-wrapper_29V76 img "
  - 
    DataType: json
    Parser: json
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 央视国内新闻
    ListUrl: "https://news.cctv.com/2019/07/gaiban/cmsdatainterface/page/china_1.jsonp?cb=china"
    RawListUrl: "https://news.cctv.com/china/"
    Item: "data.list"
    NewsUrl: "url"
    Title: "title"
    Rank: ""
    Author: ""
    PublishTime: "focus_date"
    Abstract: "brief"
    IsHot: ""
    ImgUrl: "image"
  - 
    DataType: json
    Parser: json
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 央视国际新闻
    ListUrl: "https://news.cctv.com/2019/07/gaiban/cmsdatainterface/page/world_1.jsonp?cb=world"
    RawListUrl: "https://news.cctv.com/world/"
    Item: "data.list"
    NewsUrl: "url"
    Title: "title"
    Rank: ""
    Author: ""
    PublishTime: "focus_date"
    Abstract: "brief"
    IsHot: ""
    ImgUrl: "image"
  - 
    DataType: json
    Parser: json
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 环球网国际新闻
    ListUrl: "https://world.huanqiu.com/api/list?node=%22/e3pmh22ph/e3pmh2398%22,%22/e3pmh22ph/e3pmh26vv%22,%22/e3pmh22ph/e3pn6efsl%22,%22/e3pmh22ph/efp8fqe21%22&offset=0&limit=20"
    RawListUrl: "https://world.huanqiu.com/"
    Item: "list"
    NewsUrl: "aid"
    Title: "title"
    Rank: ""
    Author: ""
    PublishTime: "ctime"
    Abstract: "summary"
    IsHot: ""
    ImgUrl: "image"
  - 
    DataType: json
    Parser: json
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 环球网国内新闻
    ListUrl: "https://china.huanqiu.com/api/list?node=%22/e3pmh1nnq/e3pmh1obd%22,%22/e3pmh1nnq/e3pn61c2g%22,%22/e3pmh1nnq/e3pn6eiep%22,%22/e3pmh1nnq/e3pra70uk%22,%22/e3pmh1nnq/e5anm31jb%22,%22/e3pmh1nnq/e7tl4e309%22&offset=0&limit=20"
    RawListUrl: "https://china.huanqiu.com/"
    Item: "list"
    NewsUrl: "aid"
    Title: "title"
    Rank: ""
    Author: ""
    PublishTime: "ctime"
    Abstract: "summary"
    IsHot: ""
    ImgUrl: "image"
  - 
    DataType: json
    Parser: json
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 环球网军事新闻
    ListUrl: "https://mil.huanqiu.com/api/list?node=%22/e3pmh1dm8/e3pmt7hva%22,%22/e3pmh1dm8/e3pmtdr2r%22,%22/e3pmh1dm8/e3pn62l96%22,%22/e3pmh1dm8/e3pn6f3oh%22&offset=0&limit=20"
    RawListUrl: "https://mil.huanqiu.com/"
    Item: "list"
    NewsUrl: "aid"
    Title: "title"
    Rank: ""
    Author: ""
    PublishTime: "ctime"
    Abstract: "summary"
    IsHot: ""
    ImgUrl: "image"
  - 
    DataType: json
    Parser: json
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: B站热搜
    ListUrl: "https://api.bilibili.com/x/web-interface/search/square?limit=10"
    RawListUrl: "https://www.bilibili.com/"
    Item: "data.trending.list"
    NewsUrl: "keyword"
    Title: "keyword"
    Rank: ""
    Author: ""
    PublishTime: ""
    Abstract: "show_name"
    IsHot: ""
    ImgUrl: "image"
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 人民网热点
    ListUrl: "http://www.people.com.cn/GB/59476/index.html"
    RawListUrl: "http://www.people.com.cn/GB/59476/index.html"
    Item: "li "
    NewsUrl: "a "
    Title: "a "
    Rank: ""
    Author: ""
    PublishTime: ""
    Abstract: ""
    IsHot: ""
    ImgUrl: ""
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 新华社即时新闻
    ListUrl: "http://www.xinhuanet.com/whxw.htm"
    RawListUrl: "http://www.xinhuanet.com/whxw.htm"
    Item: ".dataList .clearfix"
    NewsUrl: "a "
    Title: "a "
    Rank: ""
    Author: ""
    PublishTime: "span"
    Abstract: ""
    IsHot: ""
    ImgUrl: ""
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 新华社行业研报
    ListUrl: "http://www.news.cn/fortunepro/yanbao/index.html" 
    RawListUrl: "http://www.news.cn/fortunepro/yanbao/index.html"
    Item: "#content-list .item"
    NewsUrl: "span a "
    Title: "span a "
    Rank: ""
    Author: ""
    PublishTime: ".time"
    Abstract: ""
    IsHot: ""
    ImgUrl: ""
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 新华社财经
    ListUrl: "http://www.news.cn/fortunepro/youxuan/index.html" 
    RawListUrl: "http://www.news.cn/fortunepro/youxuan/index.html"
    Item: "#content-list .item"
    NewsUrl: "span a "
    Title: "span a "
    Rank: ""
    Author: ""
    PublishTime: ".time"
    Abstract: ""
    IsHot: ""
    ImgUrl: ""
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 新华社国际要闻
    ListUrl: "http://www.news.cn/worldpro/gjxw/index.html"
    RawListUrl: "http://www.news.cn/worldpro/gjxw/index.html"
    Item: "#content-list .item"
    NewsUrl: "span a "
    Title: "span a "
    Rank: ""
    Author: ""
    PublishTime: ".time"
    Abstract: ""
    IsHot: ""
    ImgUrl: ""
  - 
    DataType: html
    Parser: css
    StoreType: 
      - mysql
      - es
    Cron: "@every 5m"
    DataSource: 中新网即时新闻
    ListUrl: "https://www.chinanews.com.cn/scroll-news/news1.html"
    RawListUrl: "https://www.chinanews.com.cn/scroll-news/news1.html"
    Item: ".content_list ul li"
    NewsUrl: ".dd_bt a "
    Title: ".dd_bt a "
    Rank: ""
    Author: ""
    PublishTime: ".dd_time "
    Abstract: ""
    IsHot: ""
    ImgUrl: ""