definitions:
  main.NewsModel:
    properties:
      abstract:
        type: string
      author:
        type: string
      data_source:
        description: required
        type: string
      img_url:
        type: string
      is_hot:
        type: boolean
      list_url:
        description: required
        type: string
      news_url:
        description: required
        type: string
      page_url:
        description: required
        type: string
      publish_time:
        type: string
      rank:
        type: integer
      title:
        description: required
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/search/{key}:
    get:
      description: 关键词搜索新闻, 按照时间排序
      parameters:
      - description: 关键字
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/main.NewsModel'
            type: array
      summary: 关键词搜索
      tags:
      - News
swagger: "2.0"
